<?php require __DIR__.'/app/bootstrap.php';
$pdo=db();
$dept=$_GET['department']??''; $city=$_GET['city']??''; $priority=$_GET['priority']??''; $group=$_GET['group']??'';
$where=["r.moderation_status='published'"]; $params=[];
if($dept){$where[]='p.department_id=?';$params[]=$dept;} if($city){$where[]='p.municipality_id=?';$params[]=$city;} if($priority){$where[]='r.system_priority=?';$params[]=$priority;}
if($group==='pending')$where[]="r.status='pending'"; elseif($group==='reviewing')$where[]="r.status IN ('assigned','contacted','scheduled','reviewing','second_opinion','referred')"; elseif($group==='reviewed')$where[]="r.status IN ('reviewed','closed')";
$sql="SELECT r.*, r.status AS status, r.moderation_status AS moderation_status,p.neighborhood,p.sector,m.name municipality,d.name department,(SELECT storage_path FROM damage_photos ph WHERE ph.report_id=r.id AND ph.is_public=1 ORDER BY ph.id LIMIT 1) photo FROM damage_reports r JOIN properties p ON p.id=r.property_id JOIN municipalities m ON m.id=p.municipality_id JOIN departments d ON d.id=p.department_id WHERE ".implode(' AND ',$where)." ORDER BY FIELD(r.system_priority,'urgent','high','medium','low'), r.created_at ASC LIMIT 100";
$st=$pdo->prepare($sql);$st->execute($params);$reports=$st->fetchAll();
$stats=$pdo->query("SELECT COUNT(*) total, SUM(status='pending') pending, SUM(status IN ('assigned','contacted','scheduled','reviewing','second_opinion','referred')) reviewing, SUM(status IN ('reviewed','closed')) reviewed FROM damage_reports WHERE moderation_status='published'")->fetch();
$departments=$pdo->query("SELECT * FROM departments WHERE is_active=1 ORDER BY name")->fetchAll();
$municipalities=[];if($dept){$s=$pdo->prepare("SELECT * FROM municipalities WHERE department_id=? AND is_enabled_for_reports=1 ORDER BY name");$s->execute([$dept]);$municipalities=$s->fetchAll();}
render_header(); ?>
<section class="hero"><div class="container"><div class="row align-items-center g-4"><div class="col-lg-8"><span class="badge text-bg-danger mb-3">Registro ciudadano gratuito</span><h1 class="display-5 fw-bold">Hagamos visibles las viviendas que necesitan revisión</h1><p class="lead">Registra daños visibles, evidencia fotográfica y ubicación general para conectar casos pendientes con revisores y organizaciones.</p><div class="d-flex gap-2 flex-wrap"><a class="btn btn-primary btn-lg" href="report.php">Reportar una vivienda</a><a class="btn btn-outline-primary btn-lg" href="reviewer-register.php">Quiero ayudar como revisor</a></div></div><div class="col-lg-4"><div class="alert alert-warning"><strong>¿Hay peligro inmediato?</strong><br>Evacúa y contacta los canales oficiales de emergencia. No esperes una revisión desde esta plataforma.</div></div></div></div></section>
<div class="container py-4"><div class="row g-3 mb-4"><div class="col-6 col-lg-3"><div class="stat"><div class="fs-2 fw-bold"><?= (int)$stats['total'] ?></div><div class="text-muted">Reportes</div></div></div><div class="col-6 col-lg-3"><div class="stat"><div class="fs-2 fw-bold"><?= (int)$stats['pending'] ?></div><div class="text-muted">Pendientes</div></div></div><div class="col-6 col-lg-3"><div class="stat"><div class="fs-2 fw-bold"><?= (int)$stats['reviewing'] ?></div><div class="text-muted">En revisión</div></div></div><div class="col-6 col-lg-3"><div class="stat"><div class="fs-2 fw-bold"><?= (int)$stats['reviewed'] ?></div><div class="text-muted">Revisados</div></div></div></div>
<form class="card card-body mb-3" method="get"><div class="row g-2"><div class="col-md-3"><select class="form-select" name="department" data-department><option value="">Todos los departamentos</option><?php foreach($departments as $d):?><option value="<?=$d['id']?>" <?=$dept==$d['id']?'selected':''?>><?=e($d['name'])?></option><?php endforeach?></select></div><div class="col-md-3"><select class="form-select" name="city" data-municipality><option value="">Todas las ciudades</option><?php foreach($municipalities as $m):?><option value="<?=$m['id']?>" <?=$city==$m['id']?'selected':''?>><?=e($m['name'])?></option><?php endforeach?></select></div><div class="col-md-2"><select class="form-select" name="priority"><option value="">Todas las prioridades</option><?php foreach(['urgent','high','medium','low'] as $p):?><option value="<?=$p?>" <?=$priority===$p?'selected':''?>><?=priority_label($p)?></option><?php endforeach?></select></div><div class="col-md-2"><select class="form-select" name="group"><option value="">Todos</option><option value="pending" <?=$group==='pending'?'selected':''?>>Pendientes</option><option value="reviewing" <?=$group==='reviewing'?'selected':''?>>En revisión</option><option value="reviewed" <?=$group==='reviewed'?'selected':''?>>Revisados</option></select></div><div class="col-md-2"><button class="btn btn-primary w-100">Filtrar</button></div></div></form>
<ul class="nav nav-pills mb-3"><li class="nav-item"><a class="nav-link <?=$group===''?'active':''?>" href="index.php">Todos</a></li><li class="nav-item"><a class="nav-link <?=$group==='pending'?'active':''?>" href="?group=pending">Pendientes</a></li><li class="nav-item"><a class="nav-link <?=$group==='reviewing'?'active':''?>" href="?group=reviewing">En revisión</a></li><li class="nav-item"><a class="nav-link <?=$group==='reviewed'?'active':''?>" href="?group=reviewed">Revisados</a></li></ul>
<div class="row g-3"><?php foreach($reports as $r):?><div class="col-md-6 col-lg-4"><div class="card report-card h-100"><?php if($r['photo']):?><img class="card-img-top" style="height:200px;object-fit:cover" src="<?=e($r['photo'])?>" alt="Evidencia fotográfica"><?php endif?><div class="card-body"><div class="d-flex justify-content-between gap-2"><span class="priority priority-<?=e($r['system_priority'])?>"><?=e(priority_label($r['system_priority']))?></span><span class="badge text-bg-light badge-status"><?=e(status_label($r['status']))?></span></div><h5 class="mt-2"><?=e($r['neighborhood'] ?: $r['sector'])?></h5><div class="text-muted small mb-2"><?=e($r['municipality'])?>, <?=e($r['department'])?></div><p><?=e(mb_strimwidth($r['description_public'],0,170,'…'))?></p><div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-primary" href="case.php?code=<?=urlencode($r['public_code'])?>">Ver reporte</a><?php if(is_reviewer()): $take=can_take_report($r); if($take[0]): ?><form method="post" action="take-case.php" class="m-0"><?=csrf_field()?><input type="hidden" name="report_id" value="<?=$r['id']?>"><button class="btn btn-primary">Tomar revisión</button></form><?php elseif($r['status']==='pending'): ?><span class="small text-muted align-self-center"><?=e($take[1])?></span><?php endif; endif; ?></div></div><div class="card-footer small text-muted">Reportado <?=e(date('d/m/Y H:i',strtotime($r['created_at'])))?></div></div></div><?php endforeach?></div><?php if(!$reports):?><div class="alert alert-info">No hay reportes con estos filtros.</div><?php endif?></div>
<?php render_footer(); ?>